---
# Copyright 2018-2020 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'marbot.io: Application Load Balancer (ALB) monitoring (https://github.com/marbot-io/monitoring-jump-start)'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'marbot endpoint'
      Parameters:
      - EndpointId
      - Stage
    - Label:
        default: 'ALB'
      Parameters:
      - LoadBalancerFullName
      - TargetGroupFullName
    - Label:
        default: 'Thresholds'
      Parameters:
      - ALB5XXCountThreshold
      - ALBRejectedConnectionCountThreshold
      - Target5XXCountThreshold
      - TargetConnectionErrorCountThreshold
Parameters:
  EndpointId:
    Description: 'Your marbot endpoint ID (to get this value: select a channel where marbot belongs to and send a message like this: "@marbot show me my endpoint id").'
    Type: String
  Stage:
    Description: 'marbot stage (never change this!).'
    Type: String
    Default: v1
    AllowedValues: [v1, dev]
  LoadBalancerFullName:
    Description: 'The full name of the load balancer (last part of ARN, e.g., app/load-balancer-name/1234567890123456).'
    Type: String
  TargetGroupFullName:
    Description: 'The full name of the target group (last part of ARN, e.g., targetgroup/target-group-name/1234567890123456).'
    Type: String
  ALB5XXCountThreshold:
    Description: 'The maximum number of 5XX responses from the ALB (not the targets) (set to -1 to disable).'
    Type: Number
    Default: 0
    MinValue: -1
  ALBRejectedConnectionCountThreshold:
    Description: 'The maximum number of connections that were rejected because the ALB had reached its maximum number of connections (set -1 to disable).'
    Type: Number
    Default: 0
    MinValue: -1
  Target5XXCountThreshold:
    Description: 'The maximum number of 5XX responses from the targets (set -1 to disable).'
    Type: Number
    Default: 0
    MinValue: -1
  TargetConnectionErrorCountThreshold:
    Description: 'The maximum number of connection errors from the ALB to the targets (set -1 to disable).'
    Type: Number
    Default: 0
    MinValue: -1
Conditions:
  HasALB5XXCountThreshold: !Not [!Equals [!Ref ALB5XXCountThreshold, '-1']]
  HasALBRejectedConnectionCountThreshold: !Not [!Equals [!Ref ALBRejectedConnectionCountThreshold, '-1']]
  HasTarget5XXCountThreshold: !Not [!Equals [!Ref Target5XXCountThreshold, '-1']]
  HasTargetConnectionErrorCountThreshold: !Not [!Equals [!Ref TargetConnectionErrorCountThreshold, '-1']]
Resources:
  ##########################################################################
  #                                                                        #
  #                                 TOPIC                                  #
  #                                                                        #
  ##########################################################################
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  TopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Id: Id1
        Version: '2012-10-17'
        Statement:
        - Sid: Sid1
          Effect: Allow
          Principal:
            AWS: '*' # Allow CloudWatch Alarms
          Action: 'sns:Publish'
          Resource: !Ref Topic
          Condition:
            StringEquals:
              'AWS:SourceOwner': !Ref 'AWS::AccountId'
      Topics:
      - !Ref Topic
  TopicEndpointSubscription:
    DependsOn: TopicPolicy
    Type: 'AWS::SNS::Subscription'
    Properties:
      DeliveryPolicy:
        healthyRetryPolicy:
          minDelayTarget: 1
          maxDelayTarget: 60
          numRetries: 100
          numNoDelayRetries: 0
          backoffFunction: exponential
        throttlePolicy:
          maxReceivesPerSecond: 1
      Endpoint: !Sub 'https://api.marbot.io/${Stage}/endpoint/${EndpointId}'
      Protocol: https
      TopicArn: !Ref Topic
  MonitoringJumpStartEvent:
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Monitoring Jump Start connection. (created by marbot)'
      ScheduleExpression: 'rate(30 days)'
      State: ENABLED
      Targets:
      - Arn: !Ref Topic
        Id: marbot
        Input: !Sub |
          {
            "Type": "monitoring-jump-start-connection",
            "StackTemplate": "marbot-alb",
            "StackVersion": "1.0.0",
            "Partition": "${AWS::Partition}",
            "AccountId": "${AWS::AccountId}",
            "Region": "${AWS::Region}",
            "StackId": "${AWS::StackId}",
            "StackName": "${AWS::StackName}"
          }
  ##########################################################################
  #                                                                        #
  #                                 ALARMS                                 #
  #                                                                        #
  ##########################################################################
  ALB5XXCountTooHighAlarm:
    Condition: HasALB5XXCountThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Number of 5XX responses from ALB over the last minute too high. (created by marbot)'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_ELB_5XX_Count
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      Threshold: !Ref ALB5XXCountThreshold
      ComparisonOperator: GreaterThanThreshold
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      AlarmActions:
      - !Ref Topic
      OKActions:
      - !Ref Topic
      TreatMissingData: notBreaching
  ALBRejectedConnectionCountTooHighAlarm:
    Condition: HasALBRejectedConnectionCountThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Number of rejected connections by ALB too high, ALB needs time to scale up. (created by marbot)'
      Namespace: 'AWS/ApplicationELB'
      MetricName: RejectedConnectionCount
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      Threshold: !Ref ALBRejectedConnectionCountThreshold
      ComparisonOperator: GreaterThanThreshold
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      AlarmActions:
      - !Ref Topic
      OKActions:
      - !Ref Topic
      TreatMissingData: notBreaching
  Target5XXCountTooHighAlarm:
    Condition: HasTarget5XXCountThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Number of 5XX responses from targets over the last minute too high. (created by marbot)'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_Target_5XX_Count
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      - Name: TargetGroup
        Value: !Ref TargetGroupFullName
      Threshold: !Ref Target5XXCountThreshold
      ComparisonOperator: GreaterThanThreshold
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      AlarmActions:
      - !Ref Topic
      OKActions:
      - !Ref Topic
      TreatMissingData: notBreaching
  TargetConnectionErrorCountTooHighAlarm:
    Condition: HasTargetConnectionErrorCountThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Number of rejected connections from ALB to targets over the last minute too high. (created by marbot)'
      Namespace: 'AWS/ApplicationELB'
      MetricName: TargetConnectionErrorCount
      Dimensions:
      - Name: LoadBalancer
        Value: !Ref LoadBalancerFullName
      - Name: TargetGroup
        Value: !Ref TargetGroupFullName
      Threshold: !Ref TargetConnectionErrorCountThreshold
      ComparisonOperator: GreaterThanThreshold
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      AlarmActions:
      - !Ref Topic
      OKActions:
      - !Ref Topic
      TreatMissingData: notBreaching
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  StackTemplate:
    Description: 'Stack template.'
    Value: 'marbot-alb'
  StackVersion:
    Description: 'Stack version.'
    Value: '1.0.0'
