---
name: Test

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  test:
    runs-on: 'ubuntu-18.04'

    steps:
    - name: 'Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: 'actions/checkout@v2'

    - name: Script
      run: |
        python -m pip install --upgrade pip
        pip install yamllint==1.23.0
        pip install cfn-lint==0.33.0
        yamllint *.yml
        cfn-lint -t *.yml
        find . -name 'marbot*.yml' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;
