---
name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: |
        pip install cfn-lint==0.61.0
        yamllint *.yml
        cfn-lint -t *.yml
        find . -name 'marbot*.yml' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;
        for file in marbot*.yml; do version1=$(yq e '.Outputs.StackVersion.Value' $file); version2=$(yq e '.Resources.MonitoringJumpStartEvent.Properties.Targets[0].Input' $file  | jq -r '.StackVersion'); if [ "$version1" != "$version2" ]; then echo "version $version1 does not match $version2 in $file"; exit 1; fi; done
