---
name: Test

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  test:
    runs-on: 'ubuntu-18.04'

    steps:
    - name: 'Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: 'actions/checkout@v2'

    - name: Script
      run: |
        sudo apt-get install jq
        python -m pip install --upgrade pip
        pip install yamllint==1.25.0
        pip install cfn-lint==0.40.0
        sudo wget --quiet --output-document=/usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.4.1/yq_linux_amd64
        sudo chmod +x /usr/bin/yq
        yamllint *.yml
        cfn-lint -t *.yml
        find . -name 'marbot*.yml' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;
        for file in marbot*.yml; do version1=$(yq e '.Outputs.StackVersion.Value' $file); version2=$(yq e '.Resources.MonitoringJumpStartEvent.Properties.Targets[0].Input' $file  | jq -r '.StackVersion'); if [ "$version1" != "$version2" ]; then echo "version $version1 does not match $version2 in $file"; exit 1; fi; done
